//? Structured content behind the in-app GoGo Logo reference.
//?
//? Derived from the compiler's `reserved` table and PLY grammar
//? (~/Developer/gogo-logo-compiler/tinkerlogo.py), then filtered against
//? gogo-firmware `version-3.2.6`. A command the 7.x VM does not implement falls
//? through to a terminal `default:` that halts the program with no error, so
//? only what that firmware handles is listed here. A `case` label with an empty
//? body is the same defect from the other side: `ledon` / `ledoff` dispatch and
//? do nothing, so they are left out too. `rtc_init` is the one empty case that
//? stays, because it never promised a visible action; its Notes cell says so.
//?
//? Section ids are a contract: GuideLink `to="/reference/logo#..."` points at
//? them. Renaming one silently breaks a deep link.
//?
//? Notes carry verified semantics only. An empty cell is correct where the VM
//? handler was not read; invented prose is not.

export default {
  title: 'GoGo Logo',
  lede:
    'The language the board itself runs. Program shape, port addressing, and every command ' +
    'GoGo Board 7 firmware 3.2.6 implements, with its real call form and whether it can be ' +
    'used inside an expression.',
  sections: [
    {
      id: 'shape',
      title: 'Program shape',
      blocks: [
        {
          type: 'prose',
          runs: [
            'A program is a list of procedures. Each one opens with ',
            { code: 'to' },
            ' and a name, and closes with ',
            { code: 'end' },
            '. The first procedure in the file is the entry point: the compiler ends it with ',
            { code: 'CODE_END' },
            ' and ends every later procedure with ',
            { code: 'STOP' },
            '.',
          ],
        },
        {
          type: 'note',
          tone: 'info',
          title: 'Name the first procedure autorun to run on power-up',
          runs: [
            'Calling the entry procedure ',
            { code: 'autorun' },
            ' sets the board autorun flag, so the program starts on its own after a power cycle. Any other name leaves it waiting to be started.',
          ],
        },
        {
          type: 'table',
          head: ['Form', 'Meaning'],
          mono: [0],
          rows: [
            ['to NAME :p1 :p2', 'procedure head. Parameters are declared with a leading colon'],
            ['end', 'closes a procedure'],
            ['; text', 'comment, runs to end of line'],
            ['"text"', 'string literal'],
            ['[ ... ]', 'block, passed to repeat, if, while and the event watchers'],
            ['set NAME n|s', 'assignment. The only one the language has'],
          ],
        },
        {
          type: 'prose',
          runs: [
            'Parameters are declared with a colon and read without one. ',
            { code: 'to blink :times' },
            ' declares ',
            { code: 'times' },
            '; the body writes bare ',
            { code: 'times' },
            '. The pre-scan strips a leading ',
            { code: '"' },
            ' or ',
            { code: ':' },
            ' from the declared name.',
          ],
        },
        {
          type: 'note',
          tone: 'gotcha',
          title: 'set is the only assignment',
          runs: [
            'There is no ',
            { code: 'make' },
            ' and no ',
            { code: '=' },
            ' assignment. ',
            { code: 'set counter 0' },
            ' writes, bare ',
            { code: 'counter' },
            ' reads, and ',
            { code: '=' },
            ' is the equality comparison.',
          ],
        },
      ],
    },

    {
      id: 'ports',
      title: 'Addressing ports',
      blocks: [
        {
          type: 'prose',
          runs: [
            'A port is chosen by a prefix ending in a comma, never by an argument. ',
            { code: 'output1, on' },
            ' turns motor 1 on; ',
            { code: 'on 1' },
            ' is not valid syntax. Port numbers combine, so ',
            { code: 'output123, on' },
            ' drives three motors in one statement. The board prints these numbers next to the output ports, so they are the form you can read off the hardware. The letter form ',
            { code: 'a,' },
            ' to ',
            { code: 'd,' },
            ' is the older equivalent spelling and combines the same way; older programs use it.',
          ],
        },
        {
          type: 'table',
          head: ['Prefix', 'Selects'],
          mono: [0],
          rows: [
            ['output1,  ...  output4,', 'one motor'],
            ['output12,', 'several motors at once, any combination of output1 to output4'],
            ['a,  b,  c,  d,', 'the same motors in the older letter spelling'],
            ['abc,', 'several motors by letter'],
            ['servo1,  ...  servo4,', 'one servo'],
            ['relay1,  ...  relay4,', 'one relay'],
          ],
        },
        {
          type: 'prose',
          runs: [
            'Every port also has read-back forms that name the port in the word itself: the tests ending in ',
            { code: '?' },
            ' and the plain value readers. All of them are reporters, so they sit inside an expression.',
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['output1on?', 'reporter', 'motor 1 is running. Same shape on output2 to output4, and in the letter spelling as aon?'],
            ['output1off?', 'reporter', 'motor 1 is stopped'],
            ['output1thisway?', 'reporter', 'motor 1 is turning thisway'],
            ['output1thatway?', 'reporter', 'motor 1 is turning thatway'],
            ['output1power', 'reporter', 'motor 1 power setting. This one takes a single port only, unlike the tests above'],
            ['relay1on?', 'reporter', 'relay 1 is on. Same on relay2 to relay4'],
            ['servo1angle', 'reporter', 'servo 1 angle. Same on servo2 to servo4'],
          ],
        },
        {
          type: 'prose',
          runs: [
            'The ask reporters do the same reads with the port as an ordinary numeric argument instead of a prefix, which is what you want when the port number is computed.',
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['askport n', 'reporter', 'reads a motor port'],
            ['askservo n', 'reporter', 'reads a servo port'],
            ['askrelay n', 'reporter', 'reads a relay port'],
            ['relayison n', 'reporter', 'relay n is on'],
            ['geta n', 'reporter', 'angle of servo n'],
            ['talkto n', 'statement', 'addresses a remote node'],
          ],
        },
      ],
    },

    {
      id: 'control',
      title: 'Control flow',
      blocks: [
        {
          type: 'prose',
          runs: ['Every loop and test takes its body as a bracketed block. There is no block-less form.'],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['repeat n [ ... ]', 'statement', 'runs the block n times'],
            ['forever [ ... ]', 'statement', 'runs the block until the program stops'],
            ['while n [ ... ]', 'statement', 'runs the block while the test is non-zero'],
            ['if n [ ... ]', 'statement', 'runs the block once when the test is non-zero'],
            ['ifelse n [ ... ] [ ... ]', 'statement', 'first block when true, second when false'],
            ['_if n [ ... ]', 'statement', 'starts an else-if chain; must be the first clause'],
            ['_then n [ ... ]', 'statement', 'else-if clause, zero or more, each with its own condition'],
            ['_else [ ... ]', 'statement', 'optional fallback when every condition above was false'],
            ['waituntil [ n ]', 'statement', 'blocks until the test inside the brackets is non-zero'],
            ['when n [ ... ]', 'statement', 'watcher: runs the block whenever the test becomes true'],
            ['whenoff', 'statement', 'stops the when watcher'],
            ['ifstatechange n [ ... ]', 'statement', 'runs the block when the test value changes'],
            ['dobackground [ ... ]', 'statement', 'runs the block as a background task'],
            ['dobackgroundoff', 'statement', 'stops the background task'],
            ['break', 'statement', 'leaves the innermost loop'],
            ['stop', 'statement', 'ends the current procedure'],
            ['output n|s', 'statement', 'ends the current procedure and returns a value'],
            ['wait n', 'statement', 'pauses the program for n milliseconds'],
          ],
        },
        {
          type: 'note',
          tone: 'gotcha',
          title: '_then means else if, not then',
          runs: [
            { code: '_then' },
            ' carries its own condition, so the chain reads as "else if", not "then". A chain always starts with ',
            { code: '_if' },
            ', takes zero or more ',
            { code: '_then' },
            ' clauses each with its own test, and an optional ',
            { code: '_else' },
            ' at the end. GoGoCode\'s block editor is what normally emits it.',
          ],
        },
      ],
    },

    {
      id: 'values',
      title: 'Values and operators',
      blocks: [
        {
          type: 'prose',
          runs: [
            { code: 'set NAME n|s' },
            ' writes a variable and a bare name reads it. Numbers are written plainly, text in double quotes, and a bracketed list is a block rather than a value.',
          ],
        },
        {
          type: 'prose',
          runs: ['Precedence, weakest binding at level 1 and tightest at level 10.'],
        },
        {
          type: 'table',
          head: ['Level', 'Operators'],
          mono: [1],
          rows: [
            ['1', 'or   xor'],
            ['2', 'and'],
            ['3', 'not'],
            ['4', '|   ^   &'],
            ['5', '<<   >>'],
            ['6', '<   <=   >   >=   ='],
            ['7', '+   -'],
            ['8', '*   /   %'],
            ['9', 'unary minus'],
            ['10', '**   pow'],
          ],
        },
        {
          type: 'note',
          tone: 'gotcha',
          title: 'pow is infix, and = is comparison',
          runs: [
            { code: 'pow' },
            ' is a word synonym of ',
            { code: '**' },
            ', so it is written ',
            { code: '2 pow 3' },
            ' and not as a call. And there is no ',
            { code: '==' },
            ': a single ',
            { code: '=' },
            ' compares.',
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['abs n', 'reporter', ''],
            ['sqrt n', 'reporter', ''],
            ['round n', 'reporter', ''],
            ['ceil n', 'reporter', ''],
            ['floor n', 'reporter', ''],
            ['sin n', 'reporter', ''],
            ['cos n', 'reporter', ''],
            ['tan n', 'reporter', ''],
            ['asin n', 'reporter', ''],
            ['acos n', 'reporter', ''],
            ['atan n', 'reporter', ''],
            ['min n n', 'reporter', ''],
            ['max n n', 'reporter', ''],
            ['random n', 'reporter', ''],
            ['constrain n n n', 'reporter', ''],
            ['map n n n n n', 'reporter', ''],
            ['highbyte n', 'reporter', ''],
            ['lowbyte n', 'reporter', ''],
          ],
        },
        {
          type: 'table',
          head: ['Constant', 'Kind', 'Value'],
          mono: [0, 2],
          rows: [
            ['PI', 'reporter', '3.14159265'],
            ['E', 'reporter', '2.71828183'],
            ['PHI', 'reporter', '1.61803399'],
            ['LN2', 'reporter', '0.69314718'],
            ['LN10', 'reporter', '2.30258509'],
            ['SQRT2', 'reporter', '1.41421356'],
            ['SQRT1_2', 'reporter', '0.70710678'],
            ['INFINITY', 'reporter', 'floating-point infinity'],
          ],
        },
      ],
    },

    {
      id: 'output-cmds',
      title: 'Motors, servos, relays',
      blocks: [
        {
          type: 'prose',
          runs: [
            'Each of these needs its port prefix. The signature below shows one concrete prefix; any prefix from the addressing table works in its place.',
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['output1, on', 'statement', 'runs the selected motors'],
            ['output1, off', 'statement', 'stops the selected motors'],
            ['output1, onfor n', 'statement', 'runs the selected motors, then stops them after n milliseconds'],
            ['output1, thisway', 'statement', 'sets direction. cw is the same command'],
            ['output1, thatway', 'statement', 'the opposite direction. ccw is the same command'],
            ['output1, rd', 'statement', 'reverses the current direction'],
            ['output1, setpower n', 'statement', 'power 0-100. The board reports it back as 0-255 PWM'],
            ['stopall', 'statement', 'stops every motor. Takes no prefix'],
            ['servo1, seth n', 'statement', 'angle 0-180'],
            ['servo1, seta n', 'statement', 'angle 0-180'],
            ['servo1, lt n', 'statement', 'angle 0-180, one direction'],
            ['servo1, rt n', 'statement', 'angle 0-180, the other direction'],
            ['servo1, setservopower n', 'statement', ''],
            ['relay1, relaysetpower n', 'statement', 'power 0-100, reported back as percent. A non-zero power switches the relay on'],
          ],
        },
      ],
    },

    {
      id: 'sensing',
      title: 'Sensing',
      blocks: [
        {
          type: 'prose',
          runs: [
            'Port reads come in two spellings: a numbered word, and a reader taking the port as an argument. They compile to the same thing, so pick whichever reads better at the call site.',
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['readsensor n', 'reporter', 'port 1-8'],
            ['sensorN', 'reporter', 'N = 1-8. Compiles to readsensor N'],
            ['inputN', 'reporter', 'N = 1-8. Compiles to readsensor N'],
            ['readswitch n', 'reporter', 'port 1-8'],
            ['switchN', 'reporter', 'N = 1-8. Compiles to readswitch N'],
            ['readfilteredinput n', 'reporter', 'port 1-8'],
            ['filteredinputN', 'reporter', 'N = 1-8'],
            ['readfilteredvariable n', 'reporter', ''],
            ['readboardsensor n', 'reporter', 'the sensors built into the board'],
            ['readacceleration n', 'reporter', 'one accelerometer axis'],
            ['readloudness', 'reporter', ''],
            ['ir', 'reporter', 'last code received from an infrared remote'],
            ['newir?', 'reporter', 'true while an unread ir code is waiting'],
            ['serial', 'reporter', ''],
            ['newserial?', 'reporter', ''],
            ['send n|s', 'statement', 'transmits a number or text out the serial port'],
            ['handgesture', 'reporter', ''],
            ['newhandgesture?', 'reporter', ''],
            ['boardgesture', 'reporter', ''],
            ['newboardgesture?', 'reporter', ''],
            ['timer', 'reporter', 'counts up in milliseconds'],
            ['resett', 'statement', 'zeroes the timer'],
            ['tickcount', 'reporter', ''],
            ['cleartick', 'statement', 'zeroes the tick count'],
            ['settickrate n', 'statement', ''],
            ['setinputfilter n n', 'statement', ''],
            ['setinputthreshold n n', 'statement', ''],
            ['setinputweight n n', 'statement', ''],
            ['setvariablefilter n n', 'statement', ''],
            ['setvariablethreshold n n', 'statement', ''],
            ['setvariableweight n n', 'statement', ''],
            ['resetinputminmax n', 'statement', ''],
            ['resetvariableminmax n', 'statement', ''],
          ],
        },
      ],
    },

    {
      id: 'display-sound',
      title: 'Display and sound',
      blocks: [
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['show n|s', 'statement', 'writes a number or text to the display'],
            ['cls', 'statement', 'clears the display'],
            ['textpos n n', 'statement', ''],
            ['textcolor n', 'statement', ''],
            ['bgcolor n', 'statement', ''],
            ['textstyle n', 'statement', ''],
            ['setpos n', 'statement', ''],
            ['getpos', 'reporter', ''],
            ['showimage s', 'statement', ''],
            ['assetadd n n n n n|s', 'statement', ''],
            ['assetwrite n n|s', 'statement', ''],
            ['assetread n', 'reporter', ''],
            ['beep', 'statement', 'the board buzzer'],
            ['note n n', 'statement', ''],
            ['notetempo n', 'statement', ''],
            ['play', 'statement', ''],
            ['nexttrack', 'statement', ''],
            ['prevtrack', 'statement', ''],
            ['gototrack n', 'statement', ''],
            ['erasetracks', 'statement', ''],
          ],
        },
      ],
    },

    {
      id: 'data',
      title: 'Lists, text, time',
      blocks: [
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['totext n|s', 'reporter', ''],
            ['tonumber n|s', 'reporter', ''],
            ['textlength n|s', 'reporter', ''],
            ['textat n n', 'reporter', ''],
            ['textcontains n n', 'reporter', ''],
            ['textisempty n', 'reporter', ''],
            ['textindexof n n', 'reporter', ''],
            ['textsplit n n', 'reporter', ''],
            ['substring n n n', 'reporter', ''],
            ['charcodeat n n', 'reporter', ''],
            ['fromcharcode n', 'reporter', ''],
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['list_create n ...', 'reporter', 'zero or more items'],
            ['list_push n n|s', 'statement', 'appends to the end'],
            ['list_get n n', 'reporter', ''],
            ['list_set n n n|s', 'statement', ''],
            ['list_insert n n n|s', 'statement', ''],
            ['list_remove n n', 'statement', ''],
            ['list_len n', 'reporter', ''],
            ['list_find n n|s', 'reporter', ''],
            ['list_rev n', 'statement', 'reverses in place. Also usable as a reporter'],
            ['list_random n', 'reporter', ''],
            ['list_pop_at n n', 'reporter', ''],
            ['list_pop_first n', 'reporter', ''],
            ['list_pop_last n', 'reporter', ''],
            ['aset NAME n n', 'statement', 'array write'],
            ['aget NAME n', 'reporter', 'array read'],
          ],
        },
        {
          type: 'note',
          tone: 'warn',
          title: 'The board clock starts unset',
          runs: [
            'A board whose clock was never synced reports times counted from zero, not a real date. This is the same offset that shows up in offline datalog records.',
          ],
        },
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['year', 'reporter', ''],
            ['month', 'reporter', ''],
            ['day', 'reporter', ''],
            ['dow', 'reporter', 'day of week'],
            ['hours', 'reporter', ''],
            ['minutes', 'reporter', ''],
            ['seconds', 'reporter', ''],
            ['rtc_init', 'statement', 'does nothing on GoGo Board 7. The clock syncs over NTP, so there is no clock to start. Kept because older programs call it'],
          ],
        },
      ],
    },

    {
      id: 'network',
      title: 'Broadcast, MQTT, cloud',
      blocks: [
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['connectwifi s s', 'statement', ''],
            ['setbroadcastchannel n|s', 'statement', ''],
            ['setbroadcastpassword s', 'statement', ''],
            ['broadcast s', 'statement', ''],
            ['whenreceivebroadcast s [ ... ]', 'statement', 'runs the block when a matching broadcast arrives'],
            ['setmqttbroker s', 'statement', 'also spelled setmessagebroker'],
            ['mqttpublish s n|s', 'statement', 'also spelled publishmessage'],
            ['mqttsubscribe s [ ... ]', 'statement', 'also spelled subscribemessage'],
            ['mqttmessage', 'reporter', ''],
            ['message', 'reporter', ''],
            ['sendgmessage s n|s', 'statement', ''],
            ['whenreceivegmessage s [ ... ]', 'statement', ''],
            ['gmessage s', 'reporter', ''],
            ['offlinerecord n s', 'statement', 'writes one record to the board offline datalog'],
            ['cloudrecord n s', 'statement', ''],
            ['publiccloudrecord n s s', 'statement', ''],
            ['setcloudrecorduid s', 'statement', ''],
            ['setcloudrecordlocal n', 'statement', ''],
            ['reportgrading n n', 'statement', ''],
            ['setiftttkey s', 'statement', ''],
            ['sendiftttevent s n|s', 'statement', ''],
            ['setlinetoken s s', 'statement', ''],
            ['sendlinemessage n|s', 'statement', ''],
            ['sendlineimage s n|s', 'statement', ''],
            ['sendlinesticker n n n', 'statement', ''],
          ],
        },
      ],
    },

    {
      id: 'peripherals',
      title: 'I2C, Vernier, Tasmota, keyboard',
      blocks: [
        {
          type: 'table',
          head: ['Signature', 'Kind', 'Notes'],
          mono: [0],
          rows: [
            ['i2cstart', 'statement', ''],
            ['i2cstop', 'statement', ''],
            ['i2cwrite n', 'statement', ''],
            ['i2crequest n', 'statement', ''],
            ['i2cread', 'reporter', ''],
            ['i2creadandstop', 'reporter', ''],
            ['i2c_read_register n n', 'reporter', ''],
            ['i2c_write_register n n n', 'statement', ''],
            ['vernier_sensor_value n', 'reporter', ''],
            ['vernier_sensor_unit n', 'reporter', ''],
            ['tasmotasetchannel n', 'statement', ''],
            ['tasmotasendcommand s n|s n|s', 'statement', ''],
            ['tasmotamessage s', 'reporter', ''],
            ['tasmotamessagedevice s s', 'reporter', ''],
            ['tasmotanewmessagedevice s', 'reporter', ''],
            ['tasmotawhenreceive s [ ... ]', 'statement', ''],
            ['sendkey s', 'statement', 'the board has its own keyboard HID interface'],
            ['presskey s', 'statement', ''],
            ['releasekey s', 'statement', ''],
            ['sendkeydelay n', 'statement', ''],
            ['getpower n', 'reporter', ''],
          ],
        },
      ],
    },
  ],
}
